//created on: 8-Apr-2018
package couponrules

import ca.mcgill.ecse681.lts.model.Passenger
import javax.swing.JOptionPane;

dialect "java"

rule "Grant lounge access coupon"

    when
        passenger : Passenger (passenger.getLoungeAccess()==false)
    then
    	passenger.setLoungeAccess(true);
        JOptionPane.showMessageDialog(null, "To thank you for using our Self-Adaptive Luggage Tracking System, we have granted you lounge access for your flight.\nThank you!");

end

rule "Increase weight limit"
    //include attributes such as "salience" here...
    when
        passenger : Passenger (passenger.getAirCanadaFlightCount() >= 5)
    then
    	passenger.setLuggageWeightLimit(32.0f);
        JOptionPane.showMessageDialog(null, "We see that you have flown with us " + passenger.getAirCanadaFlightCount() + " times. To thank you for your loyalty, we have increased your weight limit.\nThank you for flying with us.");

end
